---
abstract: 'generate mail tool configuration from an address book'
author:
  - 'Ricardo SIGNES, C<< <rjbs@cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.88'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: App::Addex
name: App-Addex
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Config::INI::MVP::Reader: 0.023
  Config::INI::Reader: 0.005
  File::HomeDir: 0
  File::Spec: 0
  Getopt::Long::Descriptive: 0.06
  Mixin::ExtraFields: 0.005
  Mixin::ExtraFields::Param: 0
  Text::Unidecode: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/rjbs/app-addex
version: 0.021
