--- 
abstract: generate mail tool configuration from an address book
author: 
  - Ricardo Signes <rjbs@cpan.org>
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: App-Addex
no_index: 
  directory: 
    - inc
    - t
requires: 
  Config::INI::Reader: 0.005
  File::HomeDir: 0
  File::Spec: 0
  Getopt::Long::Descriptive: 0.06
  Mixin::ExtraFields: 0.005
  Mixin::ExtraFields::Param: 0
  perl: 5.8.0
version: 0.016


